M Extension added in NRV with compliance passing.
merledu/nucleusrv pull request #39
Opened 2022-07-05 20:05 UTC by Talha-Ahmed-1

```Compare to reference files ...
Check                      DIV ... OK
Check                     DIVU ... OK
Check                     MULH ... OK
Check                   MULHSU ... OK
Check                    MULHU ... OK
Check                      MUL ... OK
Check                      REM ... OK
Check                     REMU ... OK
--------------------------------
OK: 8/8 RISCV_TARGET=nucleusrv RISCV_DEVICE=rv32i RISCV_ISA=rv32im

2022-07-07 08:18 UTC, usmnzain commented
Great work. I will review it in few days.

2022-08-05 06:42 UTC, usmnzain requested changes
Please set a more meaningful filename for `script.sh`. Maye `run_compliance.sh` ?

2022-08-08 11:05 UTC, usmnzain approved these changes

2022-08-08 11:05 UTC, merged

2025-01-15 17:21 UTC, King4819 commented
@Talha-Ahmed-1 I want to ask that why I'm trying riscv-arch-test rv32im and it's still fail, thanks !!!

```
Compare to reference files ... 

Check                      DIV12d11
< ffffffff
17d15
< 7fffffff
24,26d21
< ffffffff
< 00000001
< ffffffff
 ... FAIL
Check                     DIVU10d9
< 00000000
25,26d23
< 00000001
< ffffffff
49,51d45
< ffffffff
< ffffffff
< 00000000
 ... FAIL
Check                      MUL4,6d3
< 00000000
< 00000000
< 00000000
10d6
< 80000000
18d13
< 80000001
26,30d20
< ffffffff
< ffffffff
< ffffffff
< ffffffff
< ffffffff
 ... FAIL
Check                     MULH46,50d45
< ffffffff
< ffffffff
< ffffffff
< ffffffff
< ffffffff
 ... FAIL
Check                   MULHSU10,13d9
< 00000000
< 00000000
< ffffffff
< ffffffff
20d15
< 3fffffff
26,30d20
< ffffffff
< ffffffff
< ffffffff
< ffffffff
< ffffffff
 ... FAIL
Check                    MULHU11,12d10
< 00000000
< 00000000
17,18d14
< 00000000
< 7ffffffe
26d21
< ffffffff
 ... FAIL
Check                      REM5d4
< 00000000
19d17
< 00000000
23d20
< 00000000
26d22
< ffffffff
 ... FAIL
Check                     REMU49,50d48
< ffffffff
< ffffffff
 ... FAIL
--------------------------------
FAIL: 8/8 RISCV_TARGET=nucleusrv RISCV_DEVICE=rv32i RISCV_ISA=rv32im

make: *** [Makefile:86: verify] Error 1
```